#!/usr/bin/env bash
# shellcheck shell=bash
## @file tests/megalinter.bash
## @brief Exercises fmlint through a real MegaLinter plugin load.
## @details
## Runs the descriptor named by `FMLINT_DESCRIPTOR`, defaulting to the maintained
## development descriptor, and verifies both successful and failing frontmatter
## cases.  Release validation points this script at the generated descriptor so
## the exact distributed bytes and their commit-pinned runtime dependencies are
## exercised before publication.
##
## MegaLinter requires local plugin descriptors to be hosted beneath a directory
## whose name contains `mega-linter-plugin-`.  The selected descriptor is copied
## byte-for-byte into a temporary staging directory with that naming convention
## before MegaLinter loads it.  The copy is compared with the selected descriptor
## before use so the integration test still exercises the exact generated bytes.
##
## The integration test intentionally keeps MegaLinter errors enabled so a broken
## plugin cannot appear green merely because the repository configuration
## suppresses linter failures.

set -euo pipefail

readonly FMLINT_EX_NOINPUT=66
readonly FMLINT_EX_SOFTWARE=70
readonly MEGALINTER_IMAGE="${MEGALINTER_IMAGE:-ghcr.io/oxsecurity/megalinter-ci_light:v10.1.0}"
readonly FMLINT_DESCRIPTOR="${FMLINT_DESCRIPTOR:-mega-linter-plugin-fmlint/fmlint.megalinter-descriptor.yml}"
readonly PLUGIN_STAGE_DIR="test-results/mega-linter-plugin-fmlint-release"
readonly PLUGIN_STAGE_DESCRIPTOR="${PLUGIN_STAGE_DIR}/fmlint.megalinter-descriptor.yml"

## @fn stage_plugin_descriptor()
## @brief Stages the selected descriptor where MegaLinter accepts local plugins.
## @details
## Copies the selected descriptor into a test-results directory whose name
## satisfies MegaLinter's local plugin path convention, then verifies that the
## staged file is byte-identical to the selected descriptor.
##
## @par STDIN
## Nothing is read from STDIN.
## @par STDOUT
## Nothing is written to STDOUT.
## @par STDERR
## A diagnostic is written if the source descriptor is unreadable, staging fails,
## or the staged bytes differ from the source bytes.
##
## @returns Nothing is written to STDOUT.
## @retval 0 The descriptor was staged and verified.
## @retval 66 The selected descriptor is not readable.
## @retval 70 The staging directory, copy, or byte comparison failed.
stage_plugin_descriptor() {
  if [[ ! -r ${FMLINT_DESCRIPTOR} ]]; then
    printf 'Descriptor is not readable: %s\n' "${FMLINT_DESCRIPTOR}" >&2
    return "${FMLINT_EX_NOINPUT}"
  fi

  if ! mkdir -p -- "${PLUGIN_STAGE_DIR}"; then
    printf 'Unable to create plugin staging directory: %s\n' "${PLUGIN_STAGE_DIR}" >&2
    return "${FMLINT_EX_SOFTWARE}"
  fi

  if ! cp -- "${FMLINT_DESCRIPTOR}" "${PLUGIN_STAGE_DESCRIPTOR}"; then
    printf 'Unable to stage plugin descriptor: %s\n' "${FMLINT_DESCRIPTOR}" >&2
    return "${FMLINT_EX_SOFTWARE}"
  fi

  if ! cmp -s -- "${FMLINT_DESCRIPTOR}" "${PLUGIN_STAGE_DESCRIPTOR}"; then
    printf '%s\n' 'Staged plugin descriptor differs from the selected descriptor.' >&2
    return "${FMLINT_EX_SOFTWARE}"
  fi
}

## @fn run_megalinter()
## @brief Runs the staged plugin descriptor against a selected fixture set.
## @details
## Mounts the repository as MegaLinter input, loads the staged plugin descriptor,
## and leaves linter errors enabled so the process status reflects real plugin
## behavior.
##
## @param files_json JSON array accepted by MEGALINTER_FILES_TO_LINT.
##
## @par STDIN
## Nothing is read from STDIN.
## @par STDOUT
## MegaLinter writes its ordinary console report to STDOUT.
## @par STDERR
## MegaLinter and Docker diagnostics may be written to STDERR.
##
## @returns MegaLinter's console report.
## @retval 0 MegaLinter accepted every selected fixture.
## @note Non-zero Docker or MegaLinter exit statuses are propagated unchanged.
##
## @par Examples
## @code
## run_megalinter '["tests/fixtures/good.md"]'
## @endcode
run_megalinter() {
  local files_json=$1
  local plugin_uri="file://${PLUGIN_STAGE_DESCRIPTOR}"

  docker run \
    --rm \
    -v "${PWD}:/tmp/lint" \
    -w /tmp/lint \
    -e VALIDATE_ALL_CODEBASE=true \
    -e DISABLE_ERRORS=false \
    -e PRINT_ALPACA=false \
    -e SARIF_REPORTER=false \
    -e REPORT_OUTPUT_FOLDER=/tmp/megalinter-reports \
    -e "PLUGINS=[\"${plugin_uri}\"]" \
    -e ENABLE_LINTERS='["MARKDOWN_FMLINT"]' \
    -e "MEGALINTER_FILES_TO_LINT=${files_json}" \
    "${MEGALINTER_IMAGE}"
}

stage_plugin_descriptor

if ! run_megalinter '["tests/fixtures/good.md","tests/fixtures/markdown-body-is-not-yaml.md"]'; then
  printf '%s\n' 'Expected valid frontmatter fixtures to pass MegaLinter.' >&2
  exit 1
fi

if run_megalinter '["tests/fixtures/bad-frontmatter.md"]'; then
  printf '%s\n' 'Expected invalid YAML frontmatter to fail MegaLinter.' >&2
  exit 1
fi

if run_megalinter '["tests/fixtures/unterminated.md"]'; then
  printf '%s\n' 'Expected unterminated frontmatter to fail MegaLinter.' >&2
  exit 1
fi
